version: "3.9"

services:

  app:
    build: .

    container_name: express_app

    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "3000"

    depends_on:
      - mongo
      - redis

    volumes:
      - .:/app
      - uploads:/app/public/uploads

  worker:
    build: .

    container_name: email_worker

    command: npm run queue

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - redis
      - mongo

  nginx:
    build:
      context: ./nginx

    container_name: nginx

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - app

    volumes:
      - uploads:/var/www/uploads

  mongo:
    image: mongo:8

    container_name: mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7

    container_name: redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:

  mongo_data:

  redis_data:

  uploads: